version: "3.8"

services:
  app:
    image: louislam/uptime-kuma:latest
    restart: always
    volumes:
      - /home/potteradmin/volume/uptime-kuma:/app/data
    ports:
      - "3001:3001"

volumes:
  uptime-kuma:
