version: "3.8"

services:
  jenkins:
    image: jenkins:jcasc
    ports:
      - 8080:8080
      - 50000:50000
    restart: always
    entrypoint: source /data/entrypoint_overwrited.sh
    volumes:
      - jenkins_home:/var/jenkins_home
      - /:/data/
    environment:
      JENKINS_PW: /run/secrets/jenkins_password
    secrets:
      - jenkins_password

secrets:
  jenkins_password:
    external: true

volumes:
  jenkins_home:
