version: "3.2"

services:
  jenkins:
    image: jenkins:jcasc
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_PW=/run/secrets/jenkins_password
    secrets:
      - jenkins_password

secrets:
  jenkins_password:
    external: true

volumes:
  jenkins_home:
