version: "3"

services:
  jenkins:
    image: jenkins:jcasc
    ports:
      - 8080:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    secrets:
      - jenkins_password
    restart: always

secrets:
  jenkins_password:
    external: true
