version: "3.8"

services:
  jenkins:
    image: jenkins:jcasc
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins_password
    restart: always
    volumes:
      - jenkins_home:/var/jenkins_home

secrets:
  jenkins_password:
    external: true

volumes:
  jenkins_home:
