---
version: "3.5"
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Europe/Budapest
    ports:
      - 5055:5055
    volumes:
      - jellyseerr-config:/app/config
    restart: unless-stopped

volumes:
  jellyseerr-config:
    external: true
