---
version: "3.5"
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:1.3.0
    container_name: jellyseerr
    environment:
      - TZ=Europe/Budapest
    ports:
      - 5055:5055
    volumes:
      - /mnt/jellyseerr-config:/app/config
    restart: unless-stopped

volumes:
  jellyseerr-config:
