---
version: "3.5"
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    ports:
      - 5055:5055
    volumes:
      - /mnt/jellyseerr-config:/app/config
    restart: unless-stopped

volumes:
  jellyseerr-config:
