---
version: "3.5"
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:develop
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Budapest
    ports:
      - 5055:5055
    volumes:
      - /mnt/datastore/Server/docker_volumes/jellyseer:/app/config
    restart: unless-stopped
