---
version: "3.5"
services:
  radarr:
    image: linuxserver/radarr:nightly-4.4.1.6897-ls436
    container_name: radarr
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /mnt/glusterfs/volume/radarr-config:/config
      - /mnt/datastore/personal/:/data
    ports:
      - 7878:7878
    restart: unless-stopped

volumes:
  radarr-config:
