def path = "vm-image-creation/packer" 

pipeline {
    agent any
    stages {
       stage('Git checkout') {
           steps{
               cleanWs()
               checkout scm 
            }
        }
        stage('Validate') {
            steps{
               withCredentials([usernamePassword(credentialsId: 'packer_ssh', passwordVariable: 'packer_ssh_passwd', usernameVariable: 'packer_user'), usernamePassword(credentialsId: 'ps_ops_repo_cred', passwordVariable: 'pve_pass', usernameVariable: 'pve_user')]) {
                sh ("""packer validate \
                    -var 'proxmox_api_url'=https://192.168.0.100:8006/api2/json \
                    -var 'proxmox_api_token_id'=$pve_user \
                    -var 'proxmox_api_token_secret'=$pve_pass \
                    -var 'ssh_passwd=$packer_ssh_passwd' \
                    ${path}/ubuntu-22-docker/ubuntu-22-docker.pkr.hcl
                """)
               }
            }
        }
        stage('Build') {
            steps{
               withCredentials([usernamePassword(credentialsId: 'packer_ssh', passwordVariable: 'packer_ssh_passwd', usernameVariable: 'packer_user'), usernamePassword(credentialsId: 'ps_ops_repo_cred', passwordVariable: 'pve_pass', usernameVariable: 'pve_user')]) {
                sh ("""packer build \
                    -var 'proxmox_api_url'=https://192.168.0.100:8006/api2/json \
                    -var 'proxmox_api_token_id'=$pve_user \
                    -var 'proxmox_api_token_secret'=$pve_pass \
                    -var 'ssh_passwd=$packer_ssh_passwd' \
                    ${path}/ubuntu-22-docker/ubuntu-22-docker.pkr.hcl
               }
            }
        }
    }      
}