---
version: "3.2"
services:
  plex:
    image: linuxserver/plex:latest
    dns:
      - 1.0.0.1
      - 1.1.1.1
    environment:
      - PUID=1000
      - PGID=1000
      - PLEX_CLAIM=
    volumes:
      - /mnt/datastore/personal/media/series:/data/tvshows
      - /mnt/datastore/personal/media/movies:/data/movies
      - "${USERDIR}/docker/config/plex:/config"
      - "${USERDIR}/docker/config/plex/transcode:/transcode"
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
