---
version: "3.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Budapest
    volumes:
      - /mnt/datastore/Server/docker_volumes/deluge:/config
      - /mnt/datastore/Personal/Torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
