pipeline {
    agent any
    tools {
    terraform "terraform"
    }
    stages {
       stage('Git checkout') {
           steps{
               checkout scm
            }
        }
        stage('terraform format check') {
            steps{
                sh "PATH=/bin/terraform"
                sh 'terraform fmt'
                sh 'ls -ltra'
            }
        }
        stage('terraform Init') {
            steps{
                sh 'cd automations/provisioning/terraform'
                sh 'terraform init'
                sh 'ls -ltra'
            }
        }
        stage('terraform apply') {
            steps{
                sh 'terraform apply --auto-approve'
                sh 'ls -ltra'
            }
        }
        stage('cleanup') {
            steps{
             
              sh 'rm -rf automations'
            }
        }
    }

        
}