pipeline {
    agent any
    tools {
    terraform "terraform"
    }
    stages {
       stage('Git checkout') {
           steps{
               cleanWs()
               checkout scm
            }
        }
        stage('terraform format check') {
            steps{
                sh "PATH=/bin/terraform"
                sh 'cd automations/provisioning/terraform && terraform fmt'
            }
        }
        stage('terraform Init') {
            steps{
                sh 'cd automations/provisioning/terraform && terraform init'
            }
        }
        stage('terraform apply') {
            steps{
                sh 'cd automations/provisioning/terraform && timeout 1h terraform apply -var-file="credentials.tfvars" --auto-approve'
            }
        }
        stage('cleanup') {
            steps{
              cleanWs()
            }
        }
    }

        
}