def path = "vm-image-creation/packer" 

pipeline {
    agent {
        label "Jenkins host ssh"
    }
    stages {
       
        stage('Git checkout') {
            steps{
                cleanWs()
                checkout scm 
                }
            }
        
         stage('Validate') {
            steps{
                
                    withCredentials([usernamePassword(credentialsId: 'packer_ssh', passwordVariable: 'packer_ssh_passwd', usernameVariable: 'packer_user'), usernamePassword(credentialsId: 'ps_ops_pve1_api_key', passwordVariable: 'pve_pass', usernameVariable: 'pve_user')]) {
                     sh ("""packer validate \
                         -var 'proxmox_api_url'=https://192.168.0.100:8006/api2/json \
                         -var 'proxmox_api_token_secret'=$pve_pass \
                         -var 'ssh_passwd'=$packer_ssh_passwd \
                         ${path}/rocky-91-docker/rocky-91-docker.pkr.hcl
                     """)
                    }
                }
            }   
         
         stage('Build') {
             steps{
               
                    withCredentials([usernamePassword(credentialsId: 'packer_ssh', passwordVariable: 'packer_ssh_passwd', usernameVariable: 'packer_user'), usernamePassword(credentialsId: 'ps_ops_pve1_api_key', passwordVariable: 'pve_pass', usernameVariable: 'pve_user')]) {
                     sh ("""packer build \
                         -var 'proxmox_api_url'=https://192.168.0.100:8006/api2/json \
                         -var 'proxmox_api_token_secret'=$pve_pass \
                         -var 'ssh_passwd'=$packer_ssh_passwd \
                         ${path}/rocky-91-docker/rocky-91-docker.pkr.hcl
                     """)
                    }
                }
            }
        
       
    }   
}