---
version: "3.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Budapest
    volumes:
      - /mnt/datastore/Server/docker_volumes/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
