---
version: "3.1"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    dns:
      - 1.0.0.1
      - 1.1.1.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Budapest
    volumes:
      - /home/potteradmin/volume/overseerr:/config
    ports:
      - 5055:5055
    restart: unless-stopped
