pipeline {
    agent any
   
    stages {
       stage('Git checkout') {
           steps{
               cleanWs()
               checkout scm
            }
        }

        stage('Validate packer file') {
            steps{
                sh "packer validate -var-file='/home/automations/provisioning/packer/credentials.pkr.hcl' /home/automations/provisioning/packer/ubuntu-server-22-04-docker/ubuntu-server-22-04-docker.pkr.hcl"
            }
        }

        stage('Build packer file') {
            steps{
                
                sh "packer build -var-file='/home/automations/provisioning/packer/credentials.pkr.hcl' /home/automations/provisioning/packer/ubuntu-server-22-04-docker/ubuntu-server-22-04-docker.pkr.hcl"
            }
        }

        stage('cleanup') {
            steps{
              cleanWs()
            }
        }
    }

        
}