def path = "automations/provisioning/packer" 

pipeline {
    agent any
   
    stages {
       stage('Git checkout') {
           steps{
               cleanWs()
               checkout scm 
               sh 'sudo cp -R ${WORKSPACE}/automations/home'
            }
        }

        stage('Validate packer file') {
            steps{
                dir ("automations/provisioning/packer"){
                    sh """packer validate \
                        -var-file='${path}/credentials.json' \
                        ${path}/rocky-linux-8-docker/packer.json\
                        -var 'ssh_passwd=$params.ssh_passwd'
                    """
                }
            }
        }

        stage('Build packer file') {
            steps{
                withCredentials([string(credentialsId: 'ssh', variable: 'ssh_passwd'){  
                    sh """PACKER_LOG=1 packer build \
                         -var-file='${path}/credentials.json' \
                         ${path}/rocky-linux-8-docker/packer.json \
                        -var 'ssh_passwd=$ssh_passwd'
                    ""
            }
        }


        stage('cleanup') {
            steps{
              cleanWs()
            }
        }
    }

        
}