def path = "/home/automations/provisioning/packer" 

pipeline {
    agent any
   
    stages {
       stage('Git checkout') {
           steps{
               cleanWs()
               checkout scm 
               sh ("sudo cp -R ${WORKSPACE}/automations /home")
            }
        }

        stage('Validate packer file') {
            steps{
               withCredentials([string(credentialsId: 'ssh', variable: 'ssh_passwd')]){
                sh ("""packer validate \
                    -var-file='${path}/credentials.pkr.hcl' \
                    -var 'ssh_passwd=$ssh_passwd' \\
                    ${path}/ubuntu-22-docker/ubuntu-22-docker.pkr.hcl
                """)
               }
            }
        }



        stage('Build packer file') {
            steps{
               withCredentials([string(credentialsId: 'ssh', variable: 'ssh_passwd')]){
                sh ("""packer build \
                    -var-file='${path}/credentials.pkr.hcl' \
                    -var 'ssh_passwd=$ssh_passwd' \
                    ${path}/ubuntu-22-docker/ubuntu-22-docker.pkr.hcl
                """)
               }
            }
        }


        stage('cleanup') {
            steps{
              sh "sudo rm -rf ${path}" 
            }
        }
    }

        
}