---
version: "3.1"
services:
  jellyfin:
    image: linuxserver/jellyfin:amd64-nightly
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /mnt/datastore/Server/docker_volumes/jellyfin:/config
      - /mnt/datastore/Personal/Torrents:/data/tvshows
      - /mnt/datastore/Personal/Torrents:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
