def path = "services/media/$params.service" 

pipeline {
    agent {
        label "swarm_master"
    }
    stages {
       
        stage('Git checkout') {
            steps{
                cleanWs()
                checkout scm 
                }
            }

        stage('Deploy') {
            steps{
                sh "docker-compose -f ${path}/docker-compose.yml up -d"
                }
            }      
        
        stage('CleanUp'){
            steps{
              cleanWs()  
            }
        }
       
    }   
}