---
version: "3.5"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /mnt/datastore/Server/docker_volumes/sonarr:/config
      - /mnt/datastore/Personal/Torrents/Series:/tvshows
      - /mnt/datastore/Personal/Torrents:/downloads/complete
    ports:
      - 8989:8989
    restart: unless-stopped
