---
version: "3.5"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /mnt/sonarr-config:/config
      - /mnt/datastore/personal/:/data
    ports:
      - 8989:8989
    restart: unless-stopped

volumes:
  sonarr-config:
