def path = "services/ops-tools/$params.service" 

pipeline {
    agent {
        label "swarm_master"
    }
    stages {
       
        stage('Git checkout') {
            steps{
                cleanWs()
                checkout scm 
                }
            }
        
        stage('Deploy') {
            steps{
                sh "docker-compose up -f ${path}/docker-compose.yml $params.service"
                }
            }      
        
        //stage('CleanUp'){
      //      steps{
       //       cleanWs()  
       //     }
      //  }
       
    }   
}