---
version: "3.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/deluge:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - WEBUI_PORT=8080
    volumes:
      - /mnt/datastore/Server/docker_volumes/deluge:/config
      - /mnt/datastore/Personal/Torrents:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
