def path = "vm-provisioning/terraform"

pipeline {
    agent {
        label "Jenkins host ssh"
    }
    stages {
       stage('Git checkout') {
           steps{
               cleanWs()
               checkout scm
               sh 'export TF_LOG=”DEBUG”'
            }
        }
       
        stage('terraform format check') {
            steps{
                dir("${path}"){
                    sh "PATH=/bin/terraform"
                    sh "sudo terraform fmt"
                }
            }
        }
        stage('terraform Init') {
            steps{
                dir("${path}"){
                    sh "sudo terraform init"
                }
            }
        }



        stage('terraform plan') {
            steps{
                withCredentials([usernamePassword(credentialsId: 'packer_ssh', passwordVariable: 'packer_ssh_passwd', usernameVariable: 'packer_user'), usernamePassword(credentialsId: 'ps_ops_pve1_api_key', passwordVariable: 'pve_pass', usernameVariable: 'pve_user')]){ 
                    dir("${path}"){
                        sh """terraform plan \
                                -var 'proxmox_api_token_secret'=$pve_pass \
                                -var 'vmid=$params.vmid' \
                                -var 'vmname=$params.vmname' \
                                -var 'cores=$params.cores' \
                                -var 'memory=$params.memory' \
                                -var 'ip=ip=$params.ip/24,gw=192.168.0.1' \
                                -var 'desc=$params.desc' \
                                -no-color \
                                -out=plan.out
                        """
                    }
                }
            }
        }

        stage('terraform apply') {
            steps{
                withCredentials([usernamePassword(credentialsId: 'packer_ssh', passwordVariable: 'packer_ssh_passwd', usernameVariable: 'packer_user'), usernamePassword(credentialsId: 'ps_ops_pve1_api_key', passwordVariable: 'pve_pass', usernameVariable: 'pve_user')]){ 
                    dir("${path}"){
                        sh """terraform apply -debug \
                             -var 'proxmox_api_token_secret'=$pve_pass \
                             -var 'vmid=$params.vmid' \
                             -var 'vmname=$params.vmname' \
                             -var 'cores=$params.cores' \
                             -var 'memory=$params.memory' \
                             -var 'ip=ip=$params.ip/24,gw=192.168.0.1' \
                             -var 'desc=$params.desc' \
                             --auto-approve
                        """
                        sh "terraform output"
                    }
                }
            }   
        }

        
        stage('Reboot VM') {
           steps{ 
            build job: 'restart proxmox vm', parameters: [
                string(name: 'vmid', value: "$params.vmid")
            ]
           }
        }
        

    }

        
}