def path = "/automations/provisioning/terraform"

pipeline {
    agent any
    tools {
    terraform "terraform"
    }
    stages {
       stage('Git checkout') {
           steps{
               cleanWs()
               checkout scm
               sh 'export TF_LOG=”DEBUG”'
            }
        }
       
        stage('terraform format check') {
            steps{
                dir("${WORKSPACE}/${path}"){
                    sh "PATH=/bin/terraform"
                    sh "sudo terraform fmt"
                }
            }
        }
        stage('terraform Init') {
            steps{
                dir("${WORKSPACE}/${path}"){
                    sh "sudo terraform init"
                }
            }
        }



        stage('terraform plan') {
            steps{
                dir("${WORKSPACE}/${path}"){
                    sh """terraform plan \
                            -var-file='credentials.tfvars' \
                            -var 'vmid=$params.vmid' \
                            -var 'vmname=$params.vmname' \
                            -var 'cores=$params.cores' \
                            -var 'memory=$params.memory' \
                            -var 'ip=ip=$params.ip/24,gw=192.168.0.1' \
                            -var 'desc=$params.desc' \
                            -no-color \
                            -out=plan.out
                    """
                }
            }
        }

        stage('terraform apply') {
            steps{
                 dir("${WORKSPACE}/${path}"){
                    sh """terraform apply \
                         -var-file='credentials.tfvars' \
                         -var 'vmid=$params.vmid' \
                         -var 'vmname=$params.vmname' \
                         -var 'cores=$params.cores' \
                         -var 'memory=$params.memory' \
                         -var 'ip=ip=$params.ip/24,gw=192.168.0.1' \
                         -var 'desc=$params.desc' \
                         --auto-approve
                    """
                    sh "terraform output"
                }
            }
        }

        
        stage('Reboot VM') {
            steps {
                sshagent(credentials : ['pve']) {
                    sh "ssh root@192.168.0.20 qm reboot $params.vmid"
                }
            }
        }
        

    }

        
}