version: "3.1"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - AUTO_UPDATE=true #optional
    volumes:
      - /mnt/datastore/Server/docker_volumes/jackett/config:/config
      - /mnt/datastore/Personal/Torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
