version: "3.1"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - AUTO_UPDATE=true #optional
    volumes:
      - /mnt/datastore/Server/docker_volumes/jackett/config:/config

    ports:
      - 9117:9117
    restart: unless-stopped
