---
version: "3.5"
services:
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - bazarr-config:/config
      - /mnt/datastore/personal/media:/data/media #optional
    ports:
      - 6767:6767
    restart: unless-stopped

volumes:
  bazarr-config:
