version: "3.8"
services:
  node-exporter:
    image: prom/node-exporter:v1.2.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"
    deploy:
      placement:
        constraints:
          - node.role==worker
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      placement:
        constraints:
          - node.role==worker
    ports:
      - "8081:8080"
  prometheus:
    image: prom/prometheus:v2.28.1
    volumes:
      - /var/lib/jenkins/workspace/Ops_Tools/Deploy/DEPLOY_SERVICE_SWARM/services/ops-tools/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    deploy:
      placement:
        constraints:
          - node.role==worker
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:8.3.0
    ports:
      - "3000:3000"
    deploy:
      placement:
        constraints:
          - node.role==worker
    volumes:
      - grafana-data:/var/lib/grafana
  alertmanager:
    image: prom/alertmanager:v0.23.0
    ports:
      - "9093:9093"
    deploy:
      placement:
        constraints:
          - node.role==worker
    volumes:
      - /var/lib/jenkins/workspace/Ops_Tools/Deploy/DEPLOY_SERVICE_SWARM/services/ops-tools/monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/data
volumes:
  grafana-data:
  alertmanager-data:
